<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <AssemblyName>LegArmorPrepatch</AssemblyName>
    <RootNamespace>Manimal.LegArmor.Prepatch</RootNamespace>
    <Nullable>disable</Nullable>
    <LangVersion>latest</LangVersion>
    <Version>$(ModVersion)</Version>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="BepInEx"><HintPath>$(SptClientRoot)\BepInEx\core\BepInEx.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Mono.Cecil"><HintPath>$(SptClientRoot)\BepInEx\core\Mono.Cecil.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="MoreBotsPrepatch"><HintPath>$(SptClientRoot)\BepInEx\patchers\MoreBotsPrepatch\MoreBotsPrepatch.dll</HintPath><Private>false</Private></Reference>
  </ItemGroup>
  <Target Name="DeployPrepatch" AfterTargets="Build" Condition="'$(DeployToLocalInstall)' == 'true'">
    <MakeDir Directories="$(SptClientRoot)\BepInEx\patchers\LegArmorPrepatch" />
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(SptClientRoot)\BepInEx\patchers\LegArmorPrepatch" />
  </Target>
</Project>
